export const GET_FOODS_REQUEST="GET_FOODS_REQUEST";
export const GET_FOODS_SUCCESS="GET_FOODS_SUCCESS";
export const GET_FOODS_FAIL="GET_FOODS_FAIL";

export const GET_FOOD_DETAILS_REQUEST="GET_FOOD_DETAILS_REQUEST";
export const GET_FOOD_DETAILS_SUCCESS="GET_FOOD_DETAILS_SUCCESS";
export const GET_FOOD_DETAILS_FAIL="GET_FOOD_DETAILS_FAIL";
export const GET_FOOD_DETAILS_RESET="GET_FOOD_DETAILS_RESET";